# Generated by Django 3.1.4 on 2021-09-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_column='log_id', max_length=20)),
                ('login_passwd', models.CharField(db_column='passwd', max_length=120)),
            ],
            options={
                'db_table': 'tb_super',
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('c_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('c_name', models.CharField(db_column='c_name', max_length=20)),
                ('c_duration', models.IntegerField(db_column='c_dur')),
                ('c_fee', models.FloatField(db_column='c_fee')),
            ],
            options={
                'db_table': 'tb_course',
            },
        ),
        migrations.CreateModel(
            name='HrDetails',
            fields=[
                ('hr_id', models.AutoField(db_column='hr_id', primary_key=True, serialize=False)),
                ('hr_name', models.CharField(db_column='hr_name', max_length=30)),
                ('hr_dob', models.CharField(db_column='hr_dob', max_length=20)),
                ('hr_qual', models.CharField(db_column='hr_qual', default='', max_length=20)),
                ('hr_gender', models.CharField(db_column='hr_gender', max_length=10)),
                ('hr_address', models.CharField(db_column='hr_add', max_length=200)),
                ('hr_email', models.CharField(db_column='hr_email', max_length=50)),
                ('hr_phno', models.CharField(db_column='hr_phno', max_length=10)),
                ('hr_pic', models.ImageField(db_column='hr_pic', upload_to='HR/')),
                ('hr_passwd', models.CharField(db_column='hr_passwd', max_length=20)),
                ('hr_join', models.CharField(db_column='hr_join', max_length=10)),
                ('hr_status', models.CharField(db_column='hr_status', default='active', max_length=30)),
            ],
            options={
                'db_table': 'tb_hr',
            },
        ),
        migrations.CreateModel(
            name='SystemDetails',
            fields=[
                ('sys_id', models.AutoField(db_column='s_id', primary_key=True, serialize=False)),
                ('lab_no', models.IntegerField(db_column='lab_no')),
                ('sys_no', models.IntegerField(db_column='s_name')),
                ('sys_status', models.CharField(db_column='s_status', default='available', max_length=20)),
            ],
            options={
                'db_table': 'tb_system',
            },
        ),
        migrations.CreateModel(
            name='TrainerDetails',
            fields=[
                ('tr_id', models.IntegerField(db_column='hr_id', primary_key=True, serialize=False)),
                ('tr_name', models.CharField(db_column='hr_name', max_length=30)),
                ('tr_dob', models.CharField(db_column='hr_dob', max_length=20)),
                ('tr_qual', models.CharField(db_column='hr_qual', default='', max_length=20)),
                ('tr_gender', models.CharField(db_column='hr_gender', max_length=10)),
                ('tr_address', models.CharField(db_column='hr_add', max_length=200)),
                ('tr_email', models.CharField(db_column='hr_email', max_length=50)),
                ('tr_phno', models.CharField(db_column='hr_phno', max_length=10)),
                ('tr_pic', models.ImageField(db_column='hr_pic', upload_to='HR/')),
                ('tr_passwd', models.CharField(db_column='hr_passwd', max_length=20)),
                ('tr_join', models.CharField(db_column='hr_join', max_length=10)),
                ('tr_status', models.CharField(db_column='hr_status', default='active', max_length=30)),
                ('tr_course', models.ForeignKey(db_column='tr_course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute_app.coursedetails')),
            ],
            options={
                'db_table': 'tb_trainer',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('s_id', models.IntegerField(db_column='s_id', primary_key=True, serialize=False)),
                ('s_name', models.CharField(db_column='s_name', max_length=30)),
                ('s_dob', models.CharField(db_column='s_dob', max_length=10)),
                ('s_gender', models.CharField(db_column='s_gender', max_length=10)),
                ('s_qual', models.CharField(db_column='s_qual', max_length=30)),
                ('s_colg', models.CharField(db_column='s_colg', max_length=50)),
                ('s_passout', models.IntegerField(db_column='s_passout')),
                ('s_join', models.CharField(db_column='s_join', max_length=10)),
                ('amt_payable', models.FloatField(db_column='amt_payable')),
                ('s_passwd', models.CharField(db_column='s_passwd', max_length=20)),
                ('balance', models.FloatField(db_column='balance')),
                ('s_completed', models.CharField(db_column='s_compl', max_length=10)),
                ('cert_req', models.IntegerField(db_column='c_req', default=0)),
                ('placed', models.IntegerField(db_column='placed', default=0)),
                ('status', models.CharField(db_column='status', default='active', max_length=20)),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.coursedetails')),
            ],
            options={
                'db_table': 'tb_student',
            },
        ),
        migrations.CreateModel(
            name='SeatingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1', models.CharField(db_column='s1', default='free', max_length=30)),
                ('slot2', models.CharField(db_column='s2', default='free', max_length=30)),
                ('slot3', models.CharField(db_column='s3', default='free', max_length=30)),
                ('slot_s1', models.ForeignKey(db_column='slot_s1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys1', to='Institute_app.studentdetails')),
                ('slot_s2', models.ForeignKey(db_column='slot_s2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys2', to='Institute_app.studentdetails')),
                ('slot_s3', models.ForeignKey(db_column='slot_s3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys3', to='Institute_app.studentdetails')),
                ('sys_id', models.ForeignKey(db_column='sys_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute_app.systemdetails')),
            ],
            options={
                'db_table': 'tb_seating',
            },
        ),
        migrations.CreateModel(
            name='ModuleDetails',
            fields=[
                ('m_id', models.AutoField(db_column='m_id', primary_key=True, serialize=False)),
                ('m_name', models.CharField(db_column='m_name', max_length=20)),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.coursedetails')),
            ],
            options={
                'db_table': 'tb_module',
            },
        ),
    ]
