# Generated by Django 3.1.4 on 2021-09-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0002_auto_20210926_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_no', models.CharField(db_column='ins_no', max_length=20)),
                ('due_date', models.CharField(db_column='due_date', max_length=10)),
                ('paid_date', models.CharField(db_column='paid_date', max_length=10)),
                ('due_amt', models.FloatField(db_column='due_amt')),
                ('paid_amt', models.FloatField(db_column='paid_amt')),
                ('comment', models.CharField(db_column='comnt', max_length=50)),
                ('mnth', models.CharField(db_column='mnth', max_length=10)),
                ('yr', models.IntegerField(db_column='yr')),
                ('pay_type', models.CharField(db_column='type', max_length=20)),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
            ],
            options={
                'db_table': 'tb_fee',
            },
        ),
    ]
