# Generated by Django 3.1.4 on 2021-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0004_studentdetails_s_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='s_address',
            field=models.CharField(db_column='s_add', default=0, max_length=200),
            preserve_default=False,
        ),
    ]
