# Generated by Django 3.1.4 on 2021-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0005_studentdetails_s_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='s_email',
            field=models.CharField(db_column='s_email', default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='s_phno',
            field=models.CharField(db_column='s_phno', default=0, max_length=10),
            preserve_default=False,
        ),
    ]
