# Generated by Django 3.1.4 on 2021-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0007_auto_20210926_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='due_amt',
            field=models.FloatField(db_column='due_amt', default=0),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='paid_amt',
            field=models.FloatField(db_column='paid_amt', default=0),
        ),
    ]
