# Generated by Django 3.1.4 on 2021-09-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0008_auto_20210926_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetails',
            name='mnth',
        ),
        migrations.RemoveField(
            model_name='feedetails',
            name='yr',
        ),
        migrations.AddField(
            model_name='trainerdetails',
            name='log_permission',
            field=models.IntegerField(db_column='log_permission', default=0),
        ),
    ]
