# Generated by Django 3.1.4 on 2021-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0009_auto_20210928_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdetails',
            name='log_permission',
            field=models.CharField(db_column='log_permission', default='', max_length=10),
        ),
    ]
