# Generated by Django 3.1.4 on 2021-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0010_auto_20210928_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdetails',
            name='log_permission',
            field=models.IntegerField(db_column='log_permission', default=0),
        ),
    ]
