# Generated by Django 3.1.4 on 2021-09-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0011_auto_20210928_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpData',
            fields=[
                ('f_id', models.IntegerField(db_column='s_id', primary_key=True, serialize=False)),
                ('s_name', models.CharField(db_column='s_name', max_length=30)),
                ('s_dob', models.CharField(db_column='s_dob', max_length=10)),
                ('s_gender', models.CharField(db_column='s_gender', max_length=10)),
                ('s_address', models.CharField(db_column='s_add', max_length=200)),
                ('s_qual', models.CharField(db_column='s_qual', max_length=30)),
                ('s_colg', models.CharField(db_column='s_colg', max_length=50)),
                ('s_email', models.CharField(db_column='s_email', max_length=50)),
                ('s_phno', models.CharField(db_column='s_phno', max_length=10)),
                ('s_passout', models.IntegerField(db_column='s_passout')),
                ('date_entered', models.CharField(db_column='date_entered', max_length=10)),
                ('status', models.CharField(db_column='status', default='active', max_length=20)),
            ],
            options={
                'db_table': 'tb_folloupData',
            },
        ),
        migrations.CreateModel(
            name='FollowupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='date', max_length=10)),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('f_id', models.ForeignKey(db_column='f_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.followupdata')),
            ],
            options={
                'db_table': 'tb_followupStatus',
            },
        ),
    ]
