# Generated by Django 3.1.4 on 2021-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0012_followupdata_followupstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupdata',
            name='s_address',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='s_type',
            field=models.CharField(db_column='s_type', default='offline', max_length=10),
        ),
    ]
