# Generated by Django 3.1.4 on 2021-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0013_auto_20210928_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingdetails',
            name='sys_id',
        ),
        migrations.AddField(
            model_name='seatingdetails',
            name='lab_no',
            field=models.IntegerField(db_column='lab_no', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatingdetails',
            name='sys_no',
            field=models.IntegerField(db_column='s_no', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemdetails',
            name='sys_no',
            field=models.IntegerField(db_column='s_no'),
        ),
    ]
