# Generated by Django 3.1.4 on 2021-09-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0014_auto_20210928_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='type', max_length=10)),
                ('date', models.CharField(db_column='dt', max_length=10)),
                ('mnth', models.IntegerField(db_column='mnth')),
                ('yr', models.IntegerField(db_column='yr')),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('hr_id', models.ForeignKey(db_column='hr', null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute_app.hrdetails')),
                ('s_id', models.ForeignKey(db_column='st', null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
                ('tr_id', models.ForeignKey(db_column='tr', null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute_app.trainerdetails')),
            ],
            options={
                'db_table': 'tb_attendance',
            },
        ),
    ]
