# Generated by Django 3.1.4 on 2021-11-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0015_attendancedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(db_column='up_by', max_length=20)),
                ('uploaded_date', models.CharField(db_column='up_dt', max_length=20)),
                ('uploaded_file', models.FileField(upload_to='Notes/')),
                ('desc', models.CharField(db_column='desc', max_length=200)),
                ('mod_id', models.ForeignKey(db_column='mod_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.moduledetails')),
            ],
            options={
                'db_table': 'tb_notes',
            },
        ),
    ]
