# Generated by Django 3.1.4 on 2021-11-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0017_studentmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.CharField(db_column='ent_dt', max_length=20)),
                ('exam_date', models.CharField(db_column='ex_dt', max_length=20)),
                ('status', models.CharField(db_column='status', default='pending', max_length=20)),
                ('m_id', models.ForeignKey(db_column='m_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute_app.moduledetails')),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
            ],
            options={
                'db_table': 'tb_exam',
            },
        ),
    ]
