# Generated by Django 3.1.4 on 2021-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0018_examdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='pay_type',
            field=models.CharField(db_column='type', default='nil', max_length=20),
        ),
    ]
