# Generated by Django 3.1.4 on 2021-11-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0019_auto_20211107_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.CharField(db_column='req_dt', max_length=20)),
                ('rec_date', models.CharField(db_column='rec_dt', max_length=20)),
                ('hr_comment', models.CharField(db_column='hr_comnt', max_length=100)),
                ('status', models.CharField(db_column='status', default='pending', max_length=10)),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
            ],
            options={
                'db_table': 'tb_cert',
            },
        ),
    ]
