# Generated by Django 3.1.4 on 2021-11-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0020_certificatedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.CharField(db_column='add_dt', max_length=20)),
                ('interview_date', models.CharField(db_column='int_dt', max_length=20)),
                ('cmp_name', models.CharField(db_column='cmp_name', max_length=50)),
                ('cmp_addr', models.CharField(db_column='cmp_addr', max_length=100)),
                ('cmp_contact', models.CharField(db_column='cmp_cont', max_length=20)),
                ('int_type', models.CharField(db_column='int_type', max_length=10)),
                ('status', models.CharField(db_column='status', default='pending', max_length=10)),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
            ],
            options={
                'db_table': 'tb_inter',
            },
        ),
    ]
