# Generated by Django 3.1.4 on 2021-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0021_interviewdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdetails',
            name='int_post',
            field=models.CharField(db_column='int_post', default='', max_length=50),
        ),
    ]
