# Generated by Django 3.1.4 on 2021-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0022_interviewdetails_int_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='balance',
        ),
        migrations.AlterField(
            model_name='trainerdetails',
            name='tr_pic',
            field=models.ImageField(db_column='tr_pic', upload_to='Trainer/'),
        ),
    ]
