# Generated by Django 3.1.4 on 2021-12-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0023_auto_20211219_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(db_column='cmp_name', max_length=50)),
                ('designation', models.CharField(db_column='cmp_design', max_length=50)),
                ('join_date', models.CharField(db_column='cmp_join', max_length=50)),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
            ],
            options={
                'db_table': 'tb_placement',
            },
        ),
    ]
