# Generated by Django 3.1.4 on 2021-12-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0024_placementdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(db_column='cert', upload_to='Certificate/')),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Institute_app.studentdetails')),
            ],
            options={
                'db_table': 'tb_certf  ',
            },
        ),
    ]
