# Generated by Django 3.1.4 on 2021-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute_app', '0025_certfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='certfiles',
            name='cert_title',
            field=models.CharField(db_column='cert_title', max_length=30, null=True),
        ),
    ]
